### ISSUE TITLE
Tags in essentials are not cloaked.  Tags in the tags page are cloaked

### ISSUE THREAD

**Issue by ewinnerMSFT** [microsoft/azurecloak#36]
In essentials - the Tags seem to be buttons.  In the tags page they are weave pills

**Comment by gurua** [comment]
seems like it does?

![image](https://github.com/user-attachments/assets/e2fa9e0b-40a4-4bea-8edb-d3d88439dfd7)

do you have a repro?

**Comment by ewinnerMSFT** [comment]
Maybe a phone regex thing and the colon?    
![image](https://github.com/user-attachments/assets/e4ce7c37-2d85-4d12-a78a-cd0c260a3c5d)

**Comment by ewinnerMSFT** [comment]
masked in Tags blade   
![image](https://github.com/user-attachments/assets/f890ada4-f5b6-44f0-8a11-72b673fe01d5)

**Comment by ewinnerMSFT** [comment]
Fixed in phone regex
