### ISSUE TITLE
Too aggressive, masking the navigation Search Box with ********

### ISSUE THREAD

**Issue by shanselman** [microsoft/azurecloak#43]
![image](https://github.com/user-attachments/assets/818eec26-f1a2-4c07-b97d-8d93f1a50ed7)

**Comment by shanselman** [comment]
Related, it's masking dates in text boxes...that's the Shared Access Signature area for a storage account...it grabbed date/times...but not before they flashed on the screen anyway
![image](https://github.com/user-attachments/assets/5bfd0ae6-c8bf-47cc-bb2b-a07c33e2411e)

**Comment by jhochwald** [comment]
It also masquerades the name in conditional access locations. They will be shown in the overview, but are masked in the detail view.

**Comment by gurua** [comment]
This change has been reverted. Textboxes should show up normally now.
